### ISSUE TITLE
Beware when using app against multiple client databases 

### ISSUE THREAD

**Issue by alejoandez** [Geotab/real-time-map#33]
BEWARE!

In the “data-feed-getter.js” class there is a method called “initHistoricalFeedRunner()” that caches device data. Currently, If the app is used for more than one database, this cache will hold the data from multiple clients (from different databases). 

In other words, If the app is used for one client switched to pull logRecord data from another database the app will take the device Id's in the cache from previous databases and use this data to populate geolocation data for devices in the (next) currently polled database, thereby potentially mixing logRecords from two devices into one (for many devices) and this present as non-sensical trip data. Note, the object causing the issue is _configStorage.getItem(“historicalDataList”)_

Therefore if this app is intended to be used against multiple databases in a standalone application do ensure to implement correct handling of cache to account for this.

**Comment by JZ6** [comment]
Original usecase was to support only one database, but you can delete the cache if you would like to hot swap databases
